[package]
name = "vbox-proxy-server"
version = "0.1.0"
authors = ["Denys Vitali <denys.vitali@coelis.ch>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
regex = "0.2"
